/* Generated By:JavaCC: Do not edit this line. MiniScheme1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniScheme1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEMI = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int TIMES = 8;
  /** RegularExpression Id. */
  int QUOTIENT = 9;
  /** RegularExpression Id. */
  int LPAREN = 10;
  /** RegularExpression Id. */
  int RPAREN = 11;
  /** RegularExpression Id. */
  int INTEGER = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;
  /** RegularExpression Id. */
  int NEWLINE = 14;
  /** RegularExpression Id. */
  int READ = 15;
  /** RegularExpression Id. */
  int WRITE = 16;
  /** RegularExpression Id. */
  int DEFINE = 17;
  /** RegularExpression Id. */
  int SET = 18;
  /** RegularExpression Id. */
  int LET = 19;
  /** RegularExpression Id. */
  int INITIAL = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "<INTEGER>",
    "<DIGIT>",
    "\"newline\"",
    "\"read\"",
    "\"write\"",
    "\"define\"",
    "\"set!\"",
    "\"let\"",
    "<INITIAL>",
    "\".\"",
    "\"@\"",
  };

}
